/**
* Marketplace
* Marketplace - учебный проект курса \"Backend разработка на Kotlin\"
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.marketplace.kmp.transport.models


import kotlinx.serialization.*

/**
* Указание на сторону сделки объявления: предложение или потребность
* Values: DEMAND,PROPOSAL
*/

@Serializable
enum class AdDealSide(val value: kotlin.String) {


    @SerialName(value = "demand")
    DEMAND("demand"),

    @SerialName(value = "proposal")
    PROPOSAL("proposal");


    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }
}

