/**
* Marketplace
* Marketplace - учебный проект курса \"Backend разработка на Kotlin\"
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.marketplace.kmp.transport.models


import kotlinx.serialization.*

/**
* Доступы к операциям над объявлением
* Values: READ,UPDATE,CONTACT
*/

@Serializable
enum class AdPermissions(val value: kotlin.String) {


    @SerialName(value = "read")
    READ("read"),

    @SerialName(value = "update")
    UPDATE("update"),

    @SerialName(value = "contact")
    CONTACT("contact");


    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }
}

