/**
* Marketplace
* Marketplace - учебный проект курса \"Backend разработка на Kotlin\"
*
* The version of the OpenAPI document: 0.0.1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.marketplace.kmp.transport.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Описание продукта Болт
 * @param productType Идентификатор типа продукта для дискриминатора
 * @param lengh Длина болта в миллиметрах
 * @param diameter Диаметр болта в миллиметрах
 * @param threadPitch Размер резьбы
 */
@Serializable
data class AdProductBolt (
    /* Длина болта в миллиметрах */
    val lengh: Double? = null,
    /* Диаметр болта в миллиметрах */
    val diameter: Double? = null,
    /* Размер резьбы */
    val threadPitch: Double? = null,
) : AdProduct {
    override val productType: String = this::class.simpleName!!
}

