/**
* Marketplace
* Marketplace - учебный проект курса \"Backend разработка на Kotlin\"
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.marketplace.kmp.transport.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Структура с описанием страницы в ответе
 * @param size Размер запрашиваемой страницы
 * @param lastId Идентификатор последнего объекта предыдущей страницы
 * @param position 
 */
@Serializable
data class BasePaginatedResponse (
    /* Размер запрашиваемой страницы */
    @SerialName(value = "size") val size: kotlin.Int? = null,
    /* Идентификатор последнего объекта предыдущей страницы */
    @SerialName(value = "lastId") val lastId: kotlin.String? = null,
    @SerialName(value = "position") val position: BasePaginatedResponse.Position? = null
) {

    /**
     * 
     * Values: FIRST,MIDDLE,LAST
     */
    @Serializable
    enum class Position(val value: kotlin.String) {
        @SerialName(value = "first") FIRST("first"),
        @SerialName(value = "middle") MIDDLE("middle"),
        @SerialName(value = "last") LAST("last");
    }
}

