/**
* Marketplace
* Marketplace - учебный проект курса \"Backend разработка на Kotlin\"
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.marketplace.kmp.transport.models


import kotlinx.serialization.*

/**
 * Структура с описанием запрашиваемой страницы в запросах списков
 * @param size Размер запрашиваемой страницы
 * @param lastId Идентификатор последнего объекта предыдущей страницы
 */
@Serializable
data class BasePaginatedRequest (
    /* Размер запрашиваемой страницы */
    @SerialName(value = "size") val size: kotlin.Int? = null,
    /* Идентификатор последнего объекта предыдущей страницы */
    @SerialName(value = "lastId") val lastId: kotlin.String? = null
)

