/**
* Marketplace
* Marketplace - учебный проект курса \"Backend разработка на Kotlin\"
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.marketplace.kmp.transport.models

import ru.otus.otuskotlin.marketplace.kmp.transport.models.AdDealSide
import ru.otus.otuskotlin.marketplace.kmp.transport.models.AdVisibility

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import ru.otus.otuskotlin.marketplace.kmp.transport.AdProductSerializer

/**
 * Структура с данными об объявлении для запроса о созадии
 * @param title Краткое название объявления
 * @param description Тело объявления с описанием особенностей выставляемой заявки
 * @param ownerId Идентификатор пользователя, который создал и управляет объявлением
 * @param visibility 
 * @param dealSide 
 */
@Serializable
data class CreateableAd (
    /* Краткое название объявления */
    val title: String? = null,
    /* Тело объявления с описанием особенностей выставляемой заявки */
    val description: String? = null,
    /* Идентификатор пользователя, который создал и управляет объявлением */
    val ownerId: String? = null,
    val visibility: AdVisibility? = null,
    val dealSide: AdDealSide? = null,
//    @Serializable(with = AdProductSerializer::class)
    val product: AdProduct? = null,
)

