/**
* Marketplace
* Marketplace - учебный проект курса \"Backend разработка на Kotlin\"
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.marketplace.kmp.transport.models

import ru.otus.otuskotlin.marketplace.kmp.transport.models.AdDealSide
import ru.otus.otuskotlin.marketplace.kmp.transport.models.AdVisibility

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Структура с данными об объявлении для запроса о созадии
 * @param title Краткое название объявления
 * @param description Тело объявления с описанием особенностей выставляемой заявки
 * @param ownerId Идентификатор пользователя, который создал и управляет объявлением
 * @param visibility 
 * @param dealSide 
 */
@Serializable
data class CreateableAd (
    /* Краткое название объявления */
    @SerialName(value = "title") val title: kotlin.String? = null,
    /* Тело объявления с описанием особенностей выставляемой заявки */
    @SerialName(value = "description") val description: kotlin.String? = null,
    /* Идентификатор пользователя, который создал и управляет объявлением */
    @SerialName(value = "ownerId") val ownerId: kotlin.String? = null,
    @SerialName(value = "visibility") val visibility: AdVisibility? = null,
    @SerialName(value = "dealSide") val dealSide: AdDealSide? = null
)

