/**
* Marketplace
* Marketplace - учебный проект курса \"Backend разработка на Kotlin\"
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.marketplace.kmp.transport.models

import kotlinx.serialization.*

/**
 * Структура для данных об объявлении в запросе на обновление
 * @param title Краткое название объявления
 * @param description Тело объявления с описанием особенностей выставляемой заявки
 * @param ownerId Идентификатор пользователя, который создал и управляет объявлением
 * @param visibility 
 * @param dealSide 
 * @param id Идентификатор объявления
 */
@Serializable
data class UpdateableAd (
    /* Краткое название объявления */
    val title: String? = null,
    /* Тело объявления с описанием особенностей выставляемой заявки */
    val description: String? = null,
    /* Идентификатор пользователя, который создал и управляет объявлением */
    val ownerId: String? = null,
    val visibility: AdVisibility? = null,
    val dealSide: AdDealSide? = null,
    val product: AdProduct? = null,
    /* Идентификатор объявления */
    val id: String? = null
)

