POST http://127.0.0.1:8080/ad/create
Content-Type: application/json

{
  "messageType": "CreateAdRequest",
  "requestId": "12345",
  "createAd": {
    "title": "Болт",
    "description": "КРУТЕЙШИЙ",
    "ownerId": "9435",
    "visibility": "public",
    "dealSide": "demand",
    "product": {
      "productType": "AdProductBolt",
      "threadPitch": 13.0,
      "diameter": 2.0,
      "lengh": 10.3
    }
  },
  "debug": {
    "mode": "stub",
    "stub": "success"
  }
}

### With unexisted ID
POST http://127.0.0.1:8080/ad/read
Content-Type: application/json

{
  "messageType": "ReadAdRequest",
  "requestId": "12345",
  "readAdId": "99999",
  "debug": {
    "mode": "stub",
    "stub": "success"
  }
}

### With Existed id
POST http://127.0.0.1:8080/ad/read
Content-Type: application/json

{
  "messageType": "ReadAdRequest",
  "requestId": "12345",
  "readAdId": "98765",
  "debug": {
    "mode": "stub",
    "stub": "success"
  }
}





